name: "✨ Feature Request"
description: "Create a new feature or improve one"
title: "[Feature] "
labels:
  - "enhancement"
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📝 Feature Describtion
        Clear description about the feature.

  - type: textarea
    id: motivation
    attributes:
      label: "💡 Motivation"
      description: "Explain why this feature is useful and what problems it solves."
      placeholder: "This feature would help by..."
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: "🚀 Proposed solution"
      description: "Describe a possible solution."
      placeholder: "A possible solution would be..."
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: "🔄 Alternative"
      description: "Can you think of alternative solutions? If yes, describe them."
      placeholder: "An alternative solution could be..."
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: "📎 Additional Information"
      description: "Add further details, screenshots or examples."
    validations:
      required: false
