name: "🧪 Unit Test Request"
description: "Suggest a new unit test or report missing tests."
title: "[Test] "
labels:
  - "test"
  - "enhancement"
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📝 Unit Test Describtion
        A clear and concise description of the required unit tests.

  - type: textarea
    id: test_scenario
    attributes:
      label: "🔍 Test-Scenarios"
      description: "Describe the scenarios the test should cover."
      value: |
        1. Test description:
          - Give:
          - When: 
          - Then:
        2. Test description:
          - Give:
          - When: 
          - Then:
    validations:
      required: true

  - type: textarea
    id: test_implementation
    attributes:
      label: "🛠 Implementation proposal"
      description: "If possible, provide an idea or example of the test implementation."
      placeholder: "A possible test could look like this..."
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: "📎 Additional Information"
      description: "Add any other relevant information, references, or examples."
    validations:
      required: false
